SELECT * FROM BASE_TABLE WHERE RSC_ = 'India';
SELECT * FROM POPULATION_TABLE;



CREATE OR REPLACE VIEW POPULATION AS 
SELECT * FROM BASE_TABLE 
JOIN POPULATION_TABLE 
USING (ID);

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'population'

-- EXTRACT DATA BASED ONLY YEAR 2023
SELECT 
	(TP1_JAN::BIGINT * 1000) AS TOTAL_POPULAITON,
	(MP1_::BIGINT * 1000) AS MALE_POPULATION,
	(FP1_:: BIGINT * 1000) AS FEMALE_POPULATION,
	PSR_ AS SEX_RATIO,
	PD1_ AS POPULATION_DENSITY,
	YEAR_,
	RSC_
FROM POPULATION WHERE YEAR_ = 2023
 
-- COMPARE FEMALE TO MALE RATIO WITH CHINA AND GLOBAL TREND
SELECT YEAR_:: INT AS YEAR, RSC_, ROUND((FP1_::NUMERIC / MP1_)*100, 2) AS FEMALES_PER_100_MALES 
FROM POPULATION WHERE RSC_ IN ('India','China','World') ORDER BY YEAR_, RSC_;

-- MEDIAN AGE 
SELECT YEAR_, RSC_, MA1_ FROM POPULATION WHERE RSC_ IN ('India', 'China', 'World') ORDER BY MA1_, RSC_;

-- AFTER 1970 IN CHINA BY WHAT PERCENTAGE CHINA'S MEDIAN AGE INCREASE THAN INDIA'S MEDIAN AGE? 
WITH CHINA AS ( SELECT YEAR_, MA1_ FROM POPULATION WHERE RSC_ = 'China'),
INDIA AS (SELECT YEAR_, MA1_ FROM POPULATION WHERE RSC_ = 'India')
SELECT CHINA.YEAR_, ROUND((((CHINA.MA1_ - INDIA.MA1_)/INDIA.MA1_)*100)::NUMERIC, 2) AS INCREMENT FROM CHINA JOIN INDIA USING (YEAR_);

-- HOW MUCH POPULATION GROWTH RATE CHANGE YEAR BY YEAR FOR INDIA, CHINA COMPARE WITH GLOBAL ?
SELECT * FROM POPULATION LIMIT 5;
SELECT YEAR_,RSC_, PGR_, LAG(PGR_) OVER(ORDER BY YEAR_) AS PREVIOUS_GROWTH, ROUND((PGR_ - LAG(PGR_) OVER(ORDER BY YEAR_))::NUMERIC,2) AS YEARLY_CHANGE 
FROM POPULATION WHERE RSC_ IN ('China', 'World') ORDER BY RSC_, YEAR_;

SELECT YEAR_,RSC_, PGR_, LAG(PGR_) OVER(ORDER BY YEAR_) AS PREVIOUS_GROWTH, ROUND((PGR_ - LAG(PGR_) OVER(ORDER BY YEAR_))::NUMERIC,2) AS YEARLY_CHANGE 
FROM POPULATION WHERE RSC_ IN ('India', 'World') ORDER BY RSC_, YEAR_;

-- INDIA AND CHINA SHARE ON GLOBAL POPULATION
WITH WORLD AS (SELECT YEAR_, TP1_JAN FROM POPULATION WHERE RSC_ = 'World')
SELECT C.YEAR_,RSC_, ROUND(((C.TP1_JAN::NUMERIC/W.TP1_JAN)*100), 2) AS POPULATION_SHARE FROM POPULATION C
JOIN WORLD W USING(YEAR_) WHERE RSC_ IN ('China', 'India') ORDER BY W.YEAR_;

SELECT SUM(TP1_JULY),YEAR_ FROM POPULATION GROUP BY YEAR_ ORDER BY YEAR_ DESC;


---------------------------------------------------------------------------------------------------------------------
-- FERTILITY RATE OF INDIA
SELECT * FROM FERTILITY_TABLE;

CREATE OR REPLACE VIEW FERTILITY AS 
SELECT * FROM 
BASE_TABLE JOIN FERTILITY_TABLE USING (ID);

SELECT * FROM FERTILITY;
SELECT * FROM TFR_OVERTIME;
SELECT * FROM TFR_INDIA_STATES;



-- MEDIAN TFR FOR 1950 - 1960 10 YEARS, MEDIAN TFR FOR 2010 - 2023 
-- 1. CREATE NEW COLUMN AS YEAR_GROUP BY 10 YEARS GAP
ALTER TABLE TFR_INDIA_STATES ADD YEAR_GROUP VARCHAR(64);
UPDATE TFR_INDIA_STATES SET YEAR_GROUP = 
CASE 
	WHEN
		YEAR <= 1980 THEN 'YEAR 1971-1980'
	WHEN 
		YEAR >= 1981 AND YEAR <= 1990 THEN 'YEAR 1981-1990'
	WHEN
		YEAR >= 1991 AND YEAR <= 2000 THEN 'YEAR 1991-2000'
	WHEN
		YEAR >= 2001 AND YEAR <= 2010 THEN 'YEAR 2001-2010'
	ELSE 
		'YEAR 2011-2023'
END;

-- 2. SET TFR ROUNDED UPTO 2 DECIMAL
UPDATE TFR_INDIA_STATES SET TFR = ROUND(TFR::NUMERIC, 2);

-- 3. CREATE OR REPLACE VIEW
CREATE OR REPLACE VIEW TFR_OF_INDIASTATES AS 
SELECT * FROM TFR_INDIA_STATES;

-- 4. HOW MEDIAN AGE CHANGES OVER TIME BETWEEN KERALA AND BIHAR?
SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY TFR) AS STATE_MEDIAN_TFR,YEAR_GROUP, LOCATION
FROM TFR_OF_INDIASTATES WHERE LOCATION IN ('Kerala', 'Bihar')
GROUP BY YEAR_GROUP,LOCATION ORDER BY YEAR_GROUP;


SELECT * FROM TFR_INDIA_STATES;
-- OUTPUT TOP 5 STATES BELOW REPLACEMENT LEVEL AND TOP 5 STATES ABOVE REPLACEMENT LEVEL

(SELECT LOCATION, TFR, YEAR FROM TFR_OF_INDIASTATES 
WHERE YEAR = 2023 AND TFR < 2.0 AND LOCATION <> 'India' ORDER BY TFR LIMIT 5)
UNION
(SELECT LOCATION, TFR, YEAR FROM TFR_OF_INDIASTATES 
WHERE YEAR = 2023 AND TFR > 2.0 AND LOCATION <> 'India' ORDER BY TFR DESC LIMIT 5);


-- LOW_TFR_RATE_COUNTRIES
ALTER TABLE LOW_TFR_COUNTRIES ADD COLUMN TFR_GROUP VARCHAR(64);
UPDATE LOW_TFR_COUNTRIES SET TFR_GROUP = 
	CASE 
		WHEN TFR < 1.0 THEN 'VERY_LOW_TFR'
		WHEN TFR < 1.3 AND TFR >= 1.0 THEN 'LOW_TFR'
		WHEN TFR < 1.6 AND TFR >= 1.3 THEN 'MEDIUM_TFR'
		WHEN TFR < 1.9 AND TFR >= 1.6 THEN 'HIGHER_MEDIUM_TFR'
		WHEN TFR < 2.2 AND TFR >= 1.9 THEN 'REPLACEMENT_TFR'
		ELSE 'HIHGER TFR'
	END;

ALTER TABLE LOW_TFR_COUNTRIES DROP COLUMN PC
-- UNION INDIA_STATE_TABLE BELOW 1.5 TFR WITH LOW_TFR_COUNTRIES BELOW 1.5 TFR
(SELECT LOCATION, TFR FROM TFR_INDIA_STATES 
WHERE YEAR = 2023 ORDER BY TFR LIMIT 12)
UNION
(WITH RANKCOUNTRIES AS (SELECT *, DENSE_RANK() OVER(PARTITION BY TFR_GROUP ORDER BY TFR DESC) AS RANK
FROM LOW_TFR_COUNTRIES WHERE TFR < 2.0 ORDER BY TFR)
SELECT LOCATION, TFR FROM RANKCOUNTRIES WHERE RANK = 2 ORDER BY TFR LIMIT 5);




-- CREATE MANUAL TABLE
INSERT INTO LOWTFR_COUNTRIES (LOCATION, TFR, YEAR)
VALUES
	('Italy',1.2,2023),
	('UAE',1.2,2023),
	('Japan',1.21,2023),
	('Canada',1.35,2023),
	('Norway',1.41,2023),
	('United Kingdom',1.56,2023);



SELECT * FROM LOW_TFR_COUNTRIES ORDER BY TFR DESC
TRUNCATE TABLE LOWTFR_COUNTRIES
ALTER TABLE LOWTFR_COUNTRIES DROP PC


WITH RANKCOUNTRIES AS 
		(select 
			LOCATION, 
			TFR, 
			ROW_NUMBER() OVER (ORDER BY TFR) AS RANK 
		from lowtfr_countries ORDER BY TFR),

RANKSTATES AS 
		(SELECT 
			LOCATION, 
			TFR, 
			ROW_NUMBER() OVER (ORDER BY TFR) AS RANK 
		FROM TFR_INDIA_STATES WHERE YEAR = 2023)

SELECT C.LOCATION AS COUNTTRY_LOCATION,
		C.TFR AS COUNTRY_TFR,
		S.LOCATION AS STATE_LOCATION,
		S.TFR AS STATE_TFR 
FROM RANKCOUNTRIES C JOIN RANKSTATES S USING (RANK)
ORDER BY C.RANK;


-- HOW MUCH DIFFERENCE IS RURAL TFR THAN URBAN TFR
SELECT * FROM TFR_OVERTIME ORDER BY YEAR;

WITH CTE1 AS (SELECT *, ROUND((((RURAL_TFR::NUMERIC - URBAN_TFR::NUMERIC)*100)/URBAN_TFR::NUMERIC),2) AS RURALTOURBAN_DIFF 
FROM TFR_OVERTIME WHERE YEAR = 2023 GROUP BY LOCATION,YEAR,RURAL_TFR, URBAN_TFR ORDER BY YEAR)

SELECT AVG(RURALTOURBAN_DIFF) AS RURAL_TO_URBAN_TFR_DIFFERENCE FROM CTE1; 

-- EXTRACT BIRTHS, SEX RATIO 10 YEARS GAP
SELECT (BIRTHS_::INT * 1000) AS BIRTHS, SRB_, YEAR_, RSC_ FROM FERTILITY WHERE YEAR_ IN (2023,2010,2000,1990,1980,1970,1960);

-- SEPERATE CRUDE BIRTH RATE OF INDIA WORLD CHINA
WITH INDIA_CBR AS (SELECT YEAR_, CBR_ FROM FERTILITY WHERE RSC_ = 'India'),
CHINA_CBR AS (SELECT YEAR_, CBR_ FROM FERTILITY WHERE RSC_ = 'China'),
WORLD_CBR AS (SELECT YEAR_, CBR_ FROM FERTILITY WHERE RSC_ = 'World')

SELECT 
	I.YEAR_, I.CBR_ AS INDIANCBR, 
	C.CBR_ AS CHINESECBR, 
	W.CBR_ AS WORLDCBR 
FROM INDIA_CBR I 
JOIN CHINA_CBR C 
ON I.YEAR_ = C.YEAR_ 
JOIN WORLD_CBR W 
ON C.YEAR_ = W.YEAR_;

-------------------------------------------------------------------------------------------
-- INDIA MORTAILITY RATE. 
SELECT * FROM BASE_TABLE;
SELECT * FROM MORTALITY_TABLE;

CREATE TABLE MORTALITY AS 
SELECT * FROM BASE_TABLE
JOIN 
MORTALITY_TABLE USING (ID);
SELECT * FROM MORTALITY

UPDATE MORTALITY
SET 
TD_=  TD_::BIGINT *1000,
MD_= MD_::BIGINT * 1000,
FD_= FD_::BIGINT * 1000,
IDA_= IDA_::BIGINT * 1000,
LBS_= LBS_::BIGINT * 1000,
FDA_5= FDA_5::BIGINT * 1000;

DROP TABLE MORTALITY
-- DELETE COLUMN
ALTER TABLE MORTALITY DROP COLUMN VARIANT_, DROP COLUMN LC_,DROP COLUMN IAC_3,DROP COLUMN TYPE_;
--

--SUM OF MALE LIFE EXPECTANCY AND FEMALE LIFE EXPECTANCY RELATIVE TO CHINA, WORLD
CREATE TABLE LIFE_EXPECTANCY AS
WITH WORLD AS (SELECT YEAR_, MLE_, FLE_ FROM MORTALITY WHERE RSC_ ='World'),
CHINA AS (SELECT YEAR_,MLE_, FLE_ FROM MORTALITY WHERE RSC_ = 'China'),
INDIA AS (SELECT YEAR_,MLE_, FLE_ FROM MORTALITY WHERE RSC_ = 'India')

SELECT I.YEAR_, I.MLE_ AS MLE_INDIA, I.FLE_ AS FLE_INDIA,
C.MLE_ AS MLE_CHINA, C.FLE_ AS FLE_CHINA,
W.MLE_ AS MLE_WORLD, W.FLE_ AS FLE_WORLD 
FROM WORLD W
JOIN 
CHINA C 
ON W.YEAR_ = C.YEAR_
JOIN 
INDIA I
ON C.YEAR_ = I.YEAR_;

SELECT YEAR_,
ROUND(((MLE_INDIA::NUMERIC)*100/MLE_CHINA::NUMERIC),2) AS MLE_RELATIVE_TO_CHINA,
ROUND(((MLE_INDIA::NUMERIC)*100/MLE_WORLD::NUMERIC),2) AS MLE_RELATIVE_TO_WORLD,
ROUND(((FLE_INDIA::NUMERIC)*100/FLE_CHINA::NUMERIC),2) AS FLE_RELATIVE_TO_CHINA,
ROUND(((FLE_INDIA::NUMERIC)*100/FLE_WORLD::NUMERIC),2) AS FLE_RELATIVE_TO_WORLD
FROM LIFE_EXPECTANCY;

-- ANOTHER APPROACH - 
CREATE TABLE RELATIVE_LE AS 
WITH CHINA AS (SELECT YEAR_, MLE_, FLE_ FROM MORTALITY WHERE RSC_ = 'China'),
WORLD AS (SELECT YEAR_, MLE_, FLE_ FROM MORTALITY WHERE RSC_ = 'World')

SELECT 
	P.YEAR_ AS YEAR_, 
	P.RSC_ AS REGION, 
	P.MLE_ AS MLE, 
	P.FLE_ AS FLE, 
	C.MLE_ AS CHINA_MLE, 
	C.FLE_ AS CHINA_FLE,
	W.MLE_ AS WORLD_MLE,
	W.FLE_ AS WORLD_FLE
	FROM MORTALITY P 
	JOIN CHINA C
	ON P.YEAR_ = C.YEAR_ 
	JOIN WORLD W
	ON C.YEAR_ = W.YEAR_

SELECT *, ROUND(((MLE::NUMERIC/CHINA_MLE::NUMERIC)*100),2) AS RELATIVE_MLE_CHINA,
		  ROUND(((FLE::NUMERIC/CHINA_FLE::NUMERIC)*100),2) AS RELATIVE_FLE_CHINA,
		  ROUND(((MLE::NUMERIC/WORLD_MLE::NUMERIC)*100),2) AS RELATIVE_MLE_WORLD,
		  ROUND(((FLE::NUMERIC/WORLD_FLE::NUMERIC)*100),2) AS RELATIVE_FLE_WORLD
		  FROM RELATIVE_LE



DROP TABLE RELATIVE_LE













