CREATE TABLE fertility_table (
   ID BIGINT,
   BIRTHS_ BIGINT,
   BWA_15_19 BIGINT,
   CBR_ DOUBLE PRECISION,
   TFR_ DOUBLE PRECISION,
   NRR_ DOUBLE PRECISION,
   MAC_ DOUBLE PRECISION,
   SRB_ BIGINT
)