CREATE TABLE population_table (
   ID BIGINT,
   TP1_JAN BIGINT,
   TP1_JULY BIGINT,
   MP1_ BIGINT,
   FP1_ BIGINT,
   PD1_ DOUBLE PRECISION,
   PSR_ DOUBLE PRECISION,
   MA1_ DOUBLE PRECISION,
   NCB_ BIGINT,
   RNC_ DOUBLE PRECISION,
   PC_ BIGINT,
   PGR_ DOUBLE PRECISION,
   PAD_ DOUBLE PRECISION
)